#!/usr/bin/env bash

#  ┓ ┏┓┳┳┳┓┏┓┓┏┏┓┳┓
#  ┃ ┣┫┃┃┃┃┃ ┣┫┣ ┣┫
#  ┗┛┛┗┗┛┛┗┗┛┛┗┗┛┛┗
#           by Manu

dir="$HOME/.config/rofi/app-menu/"
theme='app-menu'

## Run
uwsm app -- rofi \
  -show drun \
  -run-command "uwsm app -- {cmd}" \
  -theme ${dir}/${theme}.rasi \
  -matching prefix \
  -drun-match-fields name,generic,exec \
  -no-tokenize \
  -disable-history
