#!/bin/bash

#    ┏┓┓┏┏┓┏┓┓┏┓  ┳┳┏┓┳┓┏┓┏┳┓┏┓
#    ┃ ┣┫┣ ┃ ┃┫   ┃┃┃┃┃┃┣┫ ┃ ┣
#    ┗┛┛┗┗┛┗┛┛┗┛  ┗┛┣┛┻┛┛┗ ┻ ┗┛
#            ┏┓┏┓┳┓┳┏┓┏┳┓
#            ┗┓┃ ┣┫┃┃┃ ┃
#            ┗┛┗┛┛┗┻┣┛ ┻
#                       by Manu

updates=$(($(checkupdates | wc -l) + $(yay -Qum | wc -l)))
echo "$updates"

# Refresh waybar module by sending signal 8
pkill -SIGRTMIN+8 waybar
