#!/bin/bash

#    ┓ ┏┏┓┓ ┓ ┏┓┏┓┏┓┏┓┳┓  ┏┓┏┓┳┓┳┏┓┏┳┓
#    ┃┃┃┣┫┃ ┃ ┃┃┣┫┃┃┣ ┣┫  ┗┓┃ ┣┫┃┃┃ ┃
#    ┗┻┛┛┗┗┛┗┛┣┛┛┗┣┛┗┛┛┗  ┗┛┗┛┛┗┻┣┛ ┻
#                              by Manu

DIR=$HOME/Pictures/wallpapers/
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}

if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

swww query || swww-daemon

#change-wallpaper using swww
swww img ${DIR}/${RANDOMPICS} --transition-fps 60 --transition-type any --transition-duration 3
