#!/bin/bash

# Cartella dei wallpaper
DIR=$HOME/Pictures/wallpapers/
PICS=($(ls ${DIR}))

# Seleziona una foto casuale
RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}

# Nome del file senza estensione (senza il percorso)
BASENAME=$(basename "$RANDOMPICS" .${RANDOMPICS##*.})

# Path completo dell'immagine selezionata
IMAGE_PATH="${DIR}/${RANDOMPICS}"

# Path per il file .current_wallpaper
CURRENT_WALLPAPER_PATH="$HOME/.cache/swww/.current_wallpaper"

# Copia l'immagine selezionata nella cache come .current_wallpaper
cp "$IMAGE_PATH" "$CURRENT_WALLPAPER_PATH"

# Controlla se il processo swaybg è attivo, se sì, termina
if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

# Avvia o interroga swww-daemon
swww query || swww-daemon

# Imposta il wallpaper normale con transizioni
swww img "$IMAGE_PATH" --transition-fps 60 --transition-type any --transition-duration 3

