#!/bin/bash

if ! command -v cliamp >/dev/null 2>&1; then
    skipped "cliamp"
fi

theme_dir="$HOME/.config/cliamp/themes"
mkdir -p "$theme_dir"

cat > "$theme_dir/manu.toml" << EOF
# Omarchy theme for cliamp
# Generated by thpm — do not edit manually.

accent    = "#${normal_blue}"
bright_fg = "#${bright_white}"
fg        = "#${normal_white}"
green     = "#${normal_green}"
yellow    = "#${normal_yellow}"
red       = "#${normal_red}"
EOF

config_file="$HOME/.config/cliamp/config.toml"
if [ -f "$config_file" ]; then
    if grep -q '^theme = ' "$config_file"; then
        sed -i 's/^theme = ".*"/theme = "manu"/' "$config_file"
    else
        echo 'theme = "manu"' >> "$config_file"
    fi
fi

success "cliamp theme updated!"
exit 0
