[config]

[config.wallpaper]
command = "awww img {{ image }} --transition-type grow --transition-duration 3 --transition-fps 120 --transition-bezier 0.25,0.1,0.25,1.0 --transition-pos top-right"

[templates.hyprland]
input_path = '/home/manu/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.waybar]
input_path = '/home/manu/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.walker]
input_path = '/home/manu/.config/matugen/templates/colors.css'
output_path = '~/.config/walker/themes/manu-default/colors.css'
post_hook = 'pkill -SIGUSR2 walker'

[templates.swayosd]
input_path = '/home/manu/.config/matugen/templates/colors.css'
output_path = '~/.config/swayosd/colors.css'
post_hook = 'manu-restart-swayosd'

# GTK3 | GTK4
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-matugen.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-matugen.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# Ghostty
[templates.ghostty]
input_path = '/home/manu/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

# Btop
[templates.btop]
input_path = '/home/manu/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

# Cava
[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava || true'

[templates.mako]
input_path = '~/.config/matugen/templates/mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.neovim]
input_path = '~/.config/matugen/templates/neovim.lua'
output_path = '~/.config/nvim/generated.lua'
post_hook = 'manu-reload-nvim'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.fzf]
input_path = '~/.config/matugen/templates/fzf.sh'
output_path = '~/.config/fzf/matugen-fzf.sh'

[templates.hyprlandpreview]
input_path = "~/.config/matugen/templates/hyprlandpreview.css"
output_path = "~/.config/hyprland-preview-share-picker/hyprland-preview-share-picker.css"
ppost_hook = 'kill -f hyprland-preview-share-picker'

# [templates.spotify]
# input_path = '~/.config/matugen/templates/spicetify.ini'
# output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
# post_hook = 'spicetify watch -s 2>&1 | sed "/Reloaded Spotify/q"'
