#!/usr/bin/env bash

#  ┓ ┏┓┳┳┳┓┏┓┓┏┏┓┳┓
#  ┃ ┣┫┃┃┃┃┃ ┣┫┣ ┣┫
#  ┗┛┛┗┗┛┛┗┗┛┛┗┗┛┛┗
#           by Manu

dir="$HOME/.config/rofi/launcher/"
theme='apps-menu'

## Run
rofi \
  -show drun \
  -run-command "uwsm app -- {cmd}" \
  -theme ${dir}/${theme}.rasi
