# Catppiccin Mocha Palette
palette = "catppuccin_mocha"

add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

# Catppuccin Mocha Palette
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec" 
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adbb"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold sky)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold sky"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
read_only_style = "mauve"
style = "sky"


[git_branch]
format = "[$branch]($style) "
style = "italic sky"

[git_status]
format     = '[$all_status]($style)'
style      = "sky"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
