# /etc/default/limine
# Custom configuration file for Limine Bootloader on Arch Linux.
# This file is used by Arch Linux scripts (e.g., limine-btrfs/mkinitcpio hook)
# to generate the final configuration file at /boot/limine.conf.

# ==========================================================
# 1. CORE BOOT CONFIGURATION (Variables for the script)
# ==========================================================

# Set the path to the EFI System Partition (ESP) mount point.
# Only necessary if auto-detection fails or for BIOS/ARM/RISC-V systems.
ESP_PATH="/boot"

# Set the name displayed zufor the main OS entry in the Limine menu.
TARGET_OS_NAME="Hypruccin"

# Kernel Command Line Configuration
# KERNEL_CMDLINE[default] applies to any kernel entries without specific configuration.
# Use '+=` to append parameters.
KERNEL_CMDLINE[default]+="@@CMDLINE@@"
KERNEL_CMDLINE[default]+=" quiet splash loglevel=0 systemd.show_status=false rd.udev.log_level=0 vt.global_cursor_default=0"

# UKI (Unified Kernel Image)
# Automatically create UKIs in '$ESP_PATH/EFI/Linux/' using mkinitcpio for UEFI. (yes|no)
# ENABLE_UKI=yes
# CUSTOM_UKI_NAME="hypruccin"

# Default Boot Fallback
# Set Limine as the default boot fallback at '$ESP_PATH/EFI/BOOT/BOOTX64.EFI'. (yes|no)
# ENABLE_LIMINE_FALLBACK=yes

# Find Bootloaders
# Automatically add systemd-boot, rEFInd, or the default EFI loader if found in the ESP. (yes|no)
FIND_BOOTLOADERS=yes

# Boot Integrity Check
# Enable BLAKE2 checksum verification for bootable files. (yes|no)
# ENABLE_VERIFICATION=yes

# Kernel Entries Order
# Wildcard "*" matches any letter in kernel entry name.
# BOOT_ORDER="*, Snapshots, *fallback" 
# ENABLE_SORT=no

# Snapshot Configuration
# Set the maximum number of snapshot entries to display.
MAX_SNAPSHOT_ENTRIES=5

# Defines the format used to display snapshot entries.
SNAPSHOT_FORMAT_CHOICE=5

