$image = /home/manu/Pictures/wallpapers/forest.jpg

# Standard colors (HEX format)

$background = rgba(080906ff)

$error = rgba(fcc1b9ff)

$error_container = rgba(f65146ff)

$inverse_on_surface = rgba(252721ff)

$inverse_primary = rgba(314818ff)

$inverse_surface = rgba(e0e1d6ff)

$on_background = rgba(e0e1d6ff)

$on_error = rgba(340002ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(091400ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(040900ff)

$on_primary_fixed_variant = rgba(1f3309ff)

$on_secondary = rgba(12190cff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(090e05ff)

$on_secondary_fixed_variant = rgba(2b3422ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ccd0c2ff)

$on_tertiary = rgba(001a19ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000f0fff)

$on_tertiary_fixed_variant = rgba(0d3635ff)

$outline = rgba(a2a699ff)

$outline_variant = rgba(7a7e73ff)

$primary = rgba(b7d892ff)

$primary_container = rgba(759356ff)

$primary_fixed = rgba(c8eba3ff)

$primary_fixed_dim = rgba(accd88ff)

$scrim = rgba(000000ff)

$secondary = rgba(c6d2b5ff)

$secondary_container = rgba(848f75ff)

$secondary_fixed = rgba(d9e5c6ff)

$secondary_fixed_dim = rgba(bcc8aaff)

$shadow = rgba(000000ff)

$source_color = rgba(60902eff)

$surface = rgba(080906ff)

$surface_bright = rgba(383a33ff)

$surface_container = rgba(1b1d18ff)

$surface_container_high = rgba(262822ff)

$surface_container_highest = rgba(32342dff)

$surface_container_low = rgba(11130fff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(080906ff)

$surface_tint = rgba(accd88ff)

$surface_variant = rgba(3c3f36ff)

$tertiary = rgba(a8d7d4ff)

$tertiary_container = rgba(679390ff)

$tertiary_fixed = rgba(b9eae6ff)

$tertiary_fixed_dim = rgba(9dccc9ff)


# RGB Edition - For dynamic transparency

$background_rgb = 8, 9, 6

$error_rgb = 252, 193, 185

$error_container_rgb = 246, 81, 70

$inverse_on_surface_rgb = 37, 39, 33

$inverse_primary_rgb = 49, 72, 24

$inverse_surface_rgb = 224, 225, 214

$on_background_rgb = 224, 225, 214

$on_error_rgb = 52, 0, 2

$on_error_container_rgb = 0, 0, 0

$on_primary_rgb = 9, 20, 0

$on_primary_container_rgb = 0, 0, 0

$on_primary_fixed_rgb = 4, 9, 0

$on_primary_fixed_variant_rgb = 31, 51, 9

$on_secondary_rgb = 18, 25, 12

$on_secondary_container_rgb = 0, 0, 0

$on_secondary_fixed_rgb = 9, 14, 5

$on_secondary_fixed_variant_rgb = 43, 52, 34

$on_surface_rgb = 255, 255, 255

$on_surface_variant_rgb = 204, 208, 194

$on_tertiary_rgb = 0, 26, 25

$on_tertiary_container_rgb = 0, 0, 0

$on_tertiary_fixed_rgb = 0, 15, 15

$on_tertiary_fixed_variant_rgb = 13, 54, 53

$outline_rgb = 162, 166, 153

$outline_variant_rgb = 122, 126, 115

$primary_rgb = 183, 216, 146

$primary_container_rgb = 117, 147, 86

$primary_fixed_rgb = 200, 235, 163

$primary_fixed_dim_rgb = 172, 205, 136

$scrim_rgb = 0, 0, 0

$secondary_rgb = 198, 210, 181

$secondary_container_rgb = 132, 143, 117

$secondary_fixed_rgb = 217, 229, 198

$secondary_fixed_dim_rgb = 188, 200, 170

$shadow_rgb = 0, 0, 0

$source_color_rgb = 96, 144, 46

$surface_rgb = 8, 9, 6

$surface_bright_rgb = 56, 58, 51

$surface_container_rgb = 27, 29, 24

$surface_container_high_rgb = 38, 40, 34

$surface_container_highest_rgb = 50, 52, 45

$surface_container_low_rgb = 17, 19, 15

$surface_container_lowest_rgb = 0, 0, 0

$surface_dim_rgb = 8, 9, 6

$surface_tint_rgb = 172, 205, 136

$surface_variant_rgb = 60, 63, 54

$tertiary_rgb = 168, 215, 212

$tertiary_container_rgb = 103, 147, 144

$tertiary_fixed_rgb = 185, 234, 230

$tertiary_fixed_dim_rgb = 157, 204, 201

