--ozone-platform=wayland
--ozone-platform-hint=wayland
--use-cmd-decoder=passthrough
--enable-features=WaylandLinuxDrmSyncobj,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiOnNvidiaGPUs,NVEncoderLowLatency
