[color]
background = '{{colors.surface.default.hex}}'
foreground = '{{colors.on_surface.default.hex}}'

; gradient = 0
gradient = 1
gradient_color_1 = '{{colors.primary.default.hex}}'
gradient_color_2 = '{{colors.secondary.default.hex}}'
gradient_color_3 = '{{colors.tertiary.default.hex}}'
gradient_color_4 = '{{colors.primary_container.default.hex}}'
gradient_color_5 = '{{colors.secondary_container.default.hex}}'
gradient_color_6 = '{{colors.tertiary_container.default.hex}}'
gradient_color_7 = '{{colors.on_primary_container.default.hex}}'
gradient_color_8 = '{{colors.on_secondary_container.default.hex}}'


horizontal_gradient = 0

; horizontal_gradient = 1
horizontal_gradient_color_1 = '{{colors.primary_container.default.hex}}'
horizontal_gradient_color_2 = '{{colors.primary.default.hex}}'
horizontal_gradient_color_3 = '{{colors.on_primary_container.default.hex}}'
horizontal_gradient_color_4 = '{{colors.primary.default.hex}}'
horizontal_gradient_color_5 = '{{colors.primary_container.default.hex}}'


