$image = {{image}}

# Standard colors (HEX format)
<* for name, value in colors *>
${{name}} = rgba({{value.default.hex_stripped}}ff)
<* endfor *>

# RGB Edition - For dynamic transparency
<* for name, value in colors *>
${{name}}_rgb = {{value.default.red}}, {{value.default.green}}, {{value.default.blue}}
<* endfor *>
